name: Deploy to EC2

on:
  push:
    branches: [ main ] # main 브랜치에 코드가 push되면 자동으로 시작!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/matzip-api
            git pull origin main
            # 기존에 돌아가던 서버가 있으면 끄고, 없으면 그냥 넘어감
            sudo docker rm -f matzip-server || true
            # 최신 코드로 다시 빌드 (이미지는 matzip-api 이름 그대로 사용)
            sudo docker build -t matzip-api .
            # 서버 다시 실행
            sudo docker run -d --network="host" --name matzip-server matzip-api